* debian/control, overlayroot/hooks/overlayroot,   overlayroot/scripts/init-bottom/overlayroot:   - depend on haveged for additional entropy   - grab up to 4KB of entropy from /dev/random and stash it into     a seed in the initramfs   - load the initramfs seed and the urandom boot seed into urandom     (borrowed from the /etc/init.d/urandom script)
bzr-revno: 51

diff --git a/overlayroot/scripts/init-bottom/overlayroot b/overlayroot/scripts/init-bottom/overlayroot
--- a/overlayroot/scripts/init-bottom/overlayroot
+++ b/overlayroot/scripts/init-bottom/overlayroot
@@ -127,6 +127,12 @@ crypto_setup() {
 	local fstype="ext4" pass="" mapname="secure" mkfs="1" dev=""
 	local timeout=0
 	local entropy_sources="/proc/sys/kernel/random/boot_id /proc/sys/kernel/random/uuid /dev/urandom"
+	local seed=
+	# Seed the psuedo random number generator
+	for seed in "/.random-seed" "${ROOTMNT}/var/lib/urandom/random-seed"; do
+		[ -f "${seed}" ] && cat "${seed}" > /dev/urandom ||
+			{ log_fail "failed seeding rng with [${seed}]"; return 1; }
+	done
 	# this does necessary crypto setup and sets _RET
 	# to the appropriate block device (ie /dev/mapper/secure)
 
@@ -182,7 +188,7 @@ crypto_setup() {
 		[ "$mkfs" = "0" ] &&
 			{ log_fail "mkfs=0, but no password provided"; return 1; }
 		entropy_sources="$entropy_sources $dev"
-		local pass_file=$(mktemp /dev/.initramfs/${MYTAG}.XXXXXXXXXXXX) ||
+		local pass_file=$(mktemp /dev/.initramfs/${MYTAG}.XXXXXX) ||
 			{ log_fail "failed creation of password file"; return 1; }
 		head -c 4096 $entropy_sources > ${pass_file} ||
 			{ log_fail "failed reading entropy [$entropy_sources]"; return 1; }
