* debian/control, overlayroot/etc/overlayroot.conf,   overlayroot/hooks/overlayroot, overlayroot/scripts/init-   bottom/overlayroot:   - drop pwgen dependency   - use a new algorithm for generating cryptsetup passphrase   - document that in the config file   - need a few new executables in ramfs (head, sha512sum, mktemp)   - write the randomly generated cryptsetup passphrase to a     root-only-readable file in tmpfs
bzr-revno: 50

diff --git a/overlayroot/scripts/init-bottom/overlayroot b/overlayroot/scripts/init-bottom/overlayroot
--- a/overlayroot/scripts/init-bottom/overlayroot
+++ b/overlayroot/scripts/init-bottom/overlayroot
@@ -126,6 +126,7 @@ wait_for_dev() {
 crypto_setup() {
 	local fstype="ext4" pass="" mapname="secure" mkfs="1" dev=""
 	local timeout=0
+	local entropy_sources="/proc/sys/kernel/random/boot_id /proc/sys/kernel/random/uuid /dev/urandom"
 	# this does necessary crypto setup and sets _RET
 	# to the appropriate block device (ie /dev/mapper/secure)
 
@@ -180,10 +181,15 @@ crypto_setup() {
 	else
 		[ "$mkfs" = "0" ] &&
 			{ log_fail "mkfs=0, but no password provided"; return 1; }
-		pass=$(pwgen -s 80) ||
+		entropy_sources="$entropy_sources $dev"
+		local pass_file=$(mktemp /dev/.initramfs/${MYTAG}.XXXXXXXXXXXX) ||
+			{ log_fail "failed creation of password file"; return 1; }
+		head -c 4096 $entropy_sources > ${pass_file} ||
+			{ log_fail "failed reading entropy [$entropy_sources]"; return 1; }
+		pass=$(sha512sum ${pass_file}) ||
 			{ log_fail "failed generation of password"; return 1; }
-		printf "%s" "${pass}" > "/dev/.initramfs/.${MYTAG}.pass"
-		chmod 400 "/dev/.initramfs/.${MYTAG}.pass"
+		pass=${pass%% *}
+		printf "%s" "${pass}" > ${pass_file}
 	fi
 
 	log_warn "setting up new luks device at $dev"
