cosmetic changes
 * shorten the case prereq stuff
 * add helper functions for "log_<type>_msg ${MYTAG}:"
 * add 'fail' function for "log fail and exit 0"
 * replace 'if [ $? -ne 0 ]; then log_fail; fi'
   with $command || log_fail

bzr-revno: 5.1.4

diff --git a/overlayroot/scripts/init-bottom/overlayroot b/overlayroot/scripts/init-bottom/overlayroot
--- a/overlayroot/scripts/init-bottom/overlayroot
+++ b/overlayroot/scripts/init-bottom/overlayroot
@@ -23,26 +23,26 @@
 #    along with this program.  If not, see
 #    <http://www.gnu.org/licenses/>.
 
-# no pre requirement
-PREREQ=""
-
-prereqs()
-{
-	echo "${PREREQ}"
-}
-
 case "$1" in
-	prereqs)
-	prereqs
-	exit 0
-	;;
+ 	# no pre-reqs
+	prereqs) echo ""; exit 0;;
 esac
 
 . /scripts/functions
+
 . /conf/conf.d/overlayroot
 
 MYTAG="overlayroot"
 DISABLE_MAGIC_FILE="/disable-overlayroot"
+
+log_fail() { log_failure_msg "${MYTAG}: $*"; }
+log_success() { log_success_msg "${MYTAG}: $*"; }
+log_warn() { log_warning_msg "${MYTAG}: $*"; }
+fail() {
+	[ $# -eq 0 ] || log_fail "$@";
+	exit 0; # why do we exit success?
+}
+
 
 # parse kernel boot command line 
 OVERLAYROOT_DRIVER=
@@ -60,18 +60,18 @@ done
 
 # check if overlayroot fs is disabled
 if [ ! -z "${DISABLE_OVERLAYROOT}" ]; then
-	log_warning_msg "${MYTAG}: disabled, found boot parameter disable-overlayroot"
+	log_warn "disabled, found boot parameter disable-overlayroot"
 	exit 0
 fi
 if [ -e "${rootmnt}${DISABLE_MAGIC_FILE}" ]; then
-	log_warning_msg "${MYTAG}: disabled, found file ${rootmnt}${DISABLE_MAGIC_FILE}"
+	log_warn "disabled, found file ${rootmnt}${DISABLE_MAGIC_FILE}"
 	exit 0
 fi
 if [ -z "${OVERLAYROOT_BACKING_DEVICE}" ]; then
-	log_warning_msg "${MYTAG}: disabled, undefined OVERLAYROOT_BACKING_DEVICE"
+	log_warn "disabled, undefined OVERLAYROOT_BACKING_DEVICE"
 	exit 0
 elif [ ! -b "${OVERLAYROOT_BACKING_DEVICE}" ] && [ "${OVERLAYROOT_BACKING_DEVICE}" != "tmpfs" ]; then
-	log_warning_msg "${MYTAG}: invalid value for OVERLAYROOT_BACKING_DEVICE=${OVERLAYROOT_BACKING_DEVICE}"
+	log_warn "invalid value for OVERLAYROOT_BACKING_DEVICE=${OVERLAYROOT_BACKING_DEVICE}"
 	exit 0
 fi
 
@@ -101,25 +101,16 @@ esac
 
 
 # check if kernel module exists 
-modprobe -qb ${OVERLAYROOT_DRIVER}
-if [ $? -ne 0 ]; then
-	log_failure_msg "${MYTAG} ERROR: missing kernel module ${OVERLAYROOT_DRIVER}"
-	exit 0
-fi
+modprobe -qb ${OVERLAYROOT_DRIVER} ||
+	fail "missing kernel module ${OVERLAYROOT_DRIVER}"
 
 # make the mount point on the init root fs ${ROOT_RW}
-[ -d ${ROOT_RW} ] || mkdir -p ${ROOT_RW}
-if [ $? -ne 0 ]; then
-	log_failure_msg "${MYTAG} ERROR: failed to create ${ROOT_RW}"
-	exit 0
-fi
+[ -d ${ROOT_RW} ] || mkdir -p ${ROOT_RW} ||
+	fail "failed to create ${ROOT_RW}"
 
 # make the mount point on the init root fs ${ROOT_RO}
-[ -d ${ROOT_RO} ] || mkdir -p ${ROOT_RO}
-if [ $? -ne 0 ]; then
-	log_failure_msg "${MYTAG} ERROR: failed to create ${ROOT_RO}"
-	exit 0
-fi
+[ -d ${ROOT_RO} ] || mkdir -p ${ROOT_RO} ||
+	fail "failed to create ${ROOT_RO}"
 
 if [ -b "${OVERLAYROOT_BACKING_DEVICE}" ]; then
 	# use a backing device for overlay writes
@@ -132,8 +123,7 @@ if [ -b "${OVERLAYROOT_BACKING_DEVICE}" ]; then
 				key=${OVERLAYROOT_PASSWORD}
 				printf "%s" "${key}" | /sbin/cryptsetup luksOpen ${OVERLAYROOT_BACKING_DEVICE} ${OVERLAYROOT_MAPNAME} --key-file -
 				if [ $? -ne 0 ]; then
-					log_failure_msg "${MYTAG} ERROR: failed to open luks device"
-					exit 0
+					fail "failed to open luks device"
 				fi
 			else
 				# no password, generate randomly
@@ -143,53 +133,38 @@ if [ -b "${OVERLAYROOT_BACKING_DEVICE}" ]; then
 				# luks format backing device
 				printf "%s" "${key}" | /sbin/cryptsetup luksFormat ${OVERLAYROOT_BACKING_DEVICE} --key-file -
 				if [ $? -ne 0 ]; then
-					log_failure_msg "${MYTAG} ERROR: failed to format luks device"
-					exit 0
+					fail "failed to format luks device"
 				fi
 				# luks open backing device
 				printf "%s" "${key}" | /sbin/cryptsetup luksOpen ${OVERLAYROOT_BACKING_DEVICE} ${OVERLAYROOT_MAPNAME} --key-file -
 				if [ $? -ne 0 ]; then
-					log_failure_msg "${MYTAG} ERROR: failed to open luks device"
-					exit 0
+					fail "failed to open luks device"
 				fi
 				# format devmapped backing device
 				/sbin/mke2fs -t ${OVERLAYROOT_BACKING_FILESYSTEM} /dev/mapper/${OVERLAYROOT_MAPNAME}
 				if [ $? -ne 0 ]; then
-					log_failure_msg "${MYTAG} ERROR: failed to format filesystem"
-					exit 0
+					fail "failed to format filesystem"
 				fi
 			fi
 			# mount the devmapped backing device
-			mount /dev/mapper/${OVERLAYROOT_MAPNAME} ${ROOT_RW}
-			if [ $? -ne 0 ]; then
-				log_failure_msg "${MYTAG} ERROR: failed to mount backing device"
-				exit 0
-			fi
+			mount /dev/mapper/${OVERLAYROOT_MAPNAME} ${ROOT_RW} ||
+				fail "failed to mount backing device"
 		;;
 		*)
 			# mount the backing device
-			mount "${OVERLAYROOT_BACKING_DEVICE}" ${ROOT_RW}
-			if [ $? -ne 0 ]; then
-				log_failure_msg "${MYTAG} ERROR: failed to mount backing device"
-				exit 0
-			fi
+			mount "${OVERLAYROOT_BACKING_DEVICE}" ${ROOT_RW} ||
+				fail "failed to mount backing device"
 		;;
 	esac
 else
 	# mount a tempfs using the device name tmpfs-root at ${ROOT_RW}
-	mount -t tmpfs tmpfs-root ${ROOT_RW}
-	if [ $? -ne 0 ]; then
-		log_failure_msg "${MYTAG} ERROR: failed to create tmpfs"
-		exit 0
-	fi
+	mount -t tmpfs tmpfs-root ${ROOT_RW} ||
+		fail "failed to create tmpfs"
 fi
 
 # root is mounted on ${rootmnt}, move it to ${ROOT_RO}.
-mount --move ${rootmnt} ${ROOT_RO}
-if [ $? -ne 0 ]; then
-	log_failure_msg "${MYTAG} ERROR: failed to move root away from ${rootmnt} to ${ROOT_RO}"
-	exit 0
-fi
+mount --move ${rootmnt} ${ROOT_RO} ||
+	fail "failed to move root away from ${rootmnt} to ${ROOT_RO}"
 
 # there is nothing left at ${rootmnt} now. So for any error we get we should
 # either do recovery to restore ${rootmnt} for drop to a initramfs shell using
@@ -199,7 +174,7 @@ fi
 # mount virtual fs ${rootmnt} with rw-fs ${ROOT_RW} on top or ro-fs ${ROOT_RO}.
 mount ${MOUNT_PARMS}
 if [ $? -ne 0 ]; then
-	log_failure_msg "${MYTAG} ERROR: failed to create new ro/rw layerd ${rootmnt}"
+	log_fail "failed to create new ro/rw layerd ${rootmnt}"
 	# do recovery and try resoring the mount for ${rootmnt}
 	mount --move ${ROOT_RO} ${rootmnt}
 	if [ $? -ne 0 ]; then
@@ -220,19 +195,13 @@ fi
 
 # move mount from ${ROOT_RO} to ${rootmnt}${ROOT_RO} 
 [ -d ${rootmnt}${ROOT_RO} ] || mkdir -p ${rootmnt}${ROOT_RO}
-mount --move ${ROOT_RO} ${rootmnt}${ROOT_RO}
-if [ $? -ne 0 ]; then
-	log_failure_msg "${MYTAG} ERROR: failed to move ${ROOT_RO} to ${rootmnt}${ROOT_RO}"
-	exit 0
-fi
+mount --move ${ROOT_RO} ${rootmnt}${ROOT_RO} ||
+	fail "failed to move ${ROOT_RO} to ${rootmnt}${ROOT_RO}"
 
 # move mount from ${ROOT_RW} to ${rootmnt}${ROOT_RW} 
 [ -d ${rootmnt}${ROOT_RW} ] || mkdir -p ${rootmnt}${ROOT_RW}
-mount --move ${ROOT_RW} ${rootmnt}${ROOT_RW}
-if [ $? -ne 0 ]; then
-	s "${MYTAG}: ERROR: failed to move ${ROOT_RW} to ${rootmnt}${ROOT_RW}"
-	exit 0
-fi
+mount --move ${ROOT_RW} ${rootmnt}${ROOT_RW} ||
+	fail "failed to move ${ROOT_RW} to ${rootmnt}${ROOT_RW}"
 
 # technically, everything is set up nicely now. Since ${rootmnt} had beend 
 # mounted read-only on the initfamfs already, ${rootmnt}${ROOT_RO} is it, too.
@@ -268,22 +237,19 @@ ${ROOT} ${ROOT_RO} ${ROOT_TYPE} ${ROOT_OPTIONS} 0 0
 #  remaining entries from the original ${ROOT_RO}/etc/fstab follow.
 #
 EOF
-if [ $? -ne 0 ]; then
-	log_failure_msg "${MYTAG} ERROR: failed to modify /etc/fstab (step 1)"
-	#exit 0
-fi
+[ $? -eq 0 ] || log_fail "failed to modify /etc/fstab (step 1)"
 
 #remove root entry and swap from fstab
 cat ${rootmnt}${ROOT_RO}/etc/fstab | grep -v ' / ' | grep -v swap >>${rootmnt}/etc/fstab
 if [ $? -ne 0 ]; then
-	log_failure_msg "${MYTAG} ERROR: failed to modify etc/fstab (step 2)"
+	log_fail "failed to modify etc/fstab (step 2)"
 	#exit 0
 fi
 
 # now we are done. Additinal steps may be necessary depending on the actualy
 # distribution and/or its configuration. 
 
-log_success_msg "${MYTAG} sucessfully set up layered root fs using ${OVERLAYROOT_DRIVER}"
+log_success "sucessfully set up layered root fs using ${OVERLAYROOT_DRIVER}"
 
 exit 0 
 
