overlay-chroot: do not clean_exit twice
on the happy path, we were calling clean_exit twice.
This also makes 'error' an error message, and adds
'fail' which does "error and then fail"

bzr-revno: 5.1.34

diff --git a/overlayroot/usr/sbin/overlayroot-chroot b/overlayroot/usr/sbin/overlayroot-chroot
--- a/overlayroot/usr/sbin/overlayroot-chroot
+++ b/overlayroot/usr/sbin/overlayroot-chroot
@@ -21,8 +21,8 @@ set -e
 
 error() {
 	printf "ERROR: $@\n" 1>&2
-	exit 1
 }
+fail() { [ $# -eq 0 ] || error "$@"; exit 1; }
 
 info() {
 	printf "INFO: $@\n" 1>&2
@@ -36,16 +36,15 @@ get_lowerdir() {
 		if mountpoint "${lowerdir}" >/dev/null; then
 			_RET="${lowerdir}"
 		else
-			error "Unable to find the overlayroot lowerdir"
+			fail "Unable to find the overlayroot lowerdir"
 		fi
 	else
-		error "Unable to find an overlayroot filesystem"
+		fail "Unable to find an overlayroot filesystem"
 	fi
 }
 
 clean_exit() {
-	mounts="$1"
-	rc=0
+	local mounts="$1" rc="" d="" lowerdir=""
 	for d in ${mounts}; do
 		if mountpoint ${d} >/dev/null; then
 			umount ${d} || rc=1
@@ -53,10 +52,10 @@ clean_exit() {
 	done
 	get_lowerdir
 	lowerdir=${_RET}
-	if ! mount -o remount,ro "${lowerdir}" 2>/dev/null; then
-		info "Note that [${lowerdir}] is still mounted read/write"
+	if ! mount -o remount,ro "${lowerdir}"; then
+		error "Note that [${lowerdir}] is still mounted read/write"
 	fi
-	exit ${rc}
+	[ "$2" = "return" ] && return ${rc} || exit "${rc}"
 }
 
 # Try to find the overlayroot filesystem
@@ -65,7 +64,7 @@ lowerdir=${_RET}
 mounts=
 for d in proc run sys; do
 	if ! mountpoint "${lowerdir}/${d}" >/dev/null; then
-		mount -o bind "/${d}" "${lowerdir}/${d}" || error "Unable to bind /${d}"
+		mount -o bind "/${d}" "${lowerdir}/${d}" || fail "Unable to bind /${d}"
 		mounts="$mounts $lowerdir/$d"
 		trap "clean_exit \"${mounts}\" || true" EXIT HUP INT QUIT TERM   
 	fi
@@ -73,11 +72,12 @@ done
 
 # Remount with read/write
 mount -o remount,rw "${lowerdir}" ||
-   error "Unable to remount [${lowerdir}] writable"
+   fail "Unable to remount [${lowerdir}] writable"
 info "Chrooting into [${lowerdir}]"
 chroot ${lowerdir} "$@"
 
 # Clean up mounts on exit
-clean_exit "${mounts}"
+clean_exit "${mounts}" "return"
+trap "" EXIT HUP INT QUIT TERM
 
 # vi: ts=4 noexpandtab
