some improvements, fewer subshells
no more subshells, use 'setf' to control setting of 'set -f'.
This allows us to restore it to its previous setting.

Also
 * bug fix here for determining if the rootmnt is writable.
 * bug fix with incorrect logic on mounting rw
 * pass arguments (rootmnt) into apply_updateroot

bzr-revno: 107.2.2

diff --git a/updateroot/scripts/init-bottom/updateroot b/updateroot/scripts/init-bottom/updateroot
--- a/updateroot/scripts/init-bottom/updateroot
+++ b/updateroot/scripts/init-bottom/updateroot
@@ -26,6 +26,39 @@ prereqs() {
 
 [ "$1" != "prereqs" ] || { prereqs; exit; }
 
+setf() {
+	# setf 0|1
+	#  set pathname expansion (-f) off or on
+	#     off is an alias for 0
+	#     on is an alias for 1
+	#  stores the current setting in the unscoped variable 'setf'
+	#  returns the previous setting:
+	#     0 if pathname expansion was off
+	#     1 if pathname expansion was on
+	# setf restore [setting]
+	#  restore pathname expansion to 'setting'.
+	#  if setting is not provided, defaults to variable 'setf'
+	if [ "$1" = "restore" ]; then
+		local val=${2:-${setf:-"-"}}
+		[ "$val" = "0" ] && val="-" || val="+"
+		set ${val}f
+		return
+	fi
+
+	local f="" n="0" d=/ r="1"
+	setf="+"
+	for f in "$d/"*; do
+		[ $n -gt 1 ] && break
+		n=$(($n+1))
+	done
+	[ $n -eq 1 -a "$f" = "$d/*" ] && setf="-" && r="0"
+	case "$1" in
+		off|0) set -f;;
+		on|1) set +f;;
+	esac
+	return $r
+}
+
 debug() {
 	local v=$1
 	shift
@@ -34,7 +67,7 @@ debug() {
 }
 
 extract_urls() {
-	local target="$1" url="" zopt=""
+	local target="$1" url="" zopt="" script="" fails="" ret=""
 	shift
 	for url in "$@"; do
 		case "$url" in
@@ -46,14 +79,14 @@ extract_urls() {
 		wget "$url" -O - | tar -C "$target" -xp${zopt}f -
 	done
 	if [ ! -d "$target/.updateroot" ]; then
-		return
+		return 0
 	fi
-	(
-	set +f
+
 	fails=0
-	for script in "$target/.updateroot/"*; do
+	setf on; set -- "$target/.updateroot/"*; setf restore
+	for script in "$@"; do
 		[ -f "$script" -a -x "$script" ] || continue
-		debug "running ${script#$target} in target root"
+		debug 1 "running ${script#$target} in target root"
 		chroot "$target" "${script#$target}" || {
 			fails=$(($fails+1))
 			ret=$?
@@ -61,50 +94,59 @@ extract_urls() {
 		}
 	done
 	[ $fails -eq 0 ] || exit 1
-	)
 }
 
 apply_updateroot() {
+	local rootmnt="$1" cmdline="$2" ret=""
 	local cmdline urls
-	if ! read cmdline < /proc/cmdline; then
-		log_warn "no /proc/cmdline?"
-		return 1
+	if [ "$cmdline" = "" ]; then
+		if ! read cmdline < /proc/cmdline; then
+			log_warn "no /proc/cmdline?"
+			return 1
+		fi
 	fi
-	set -f
-	for tok in $cmdline; do
+	setf off; set -- $cmdline; setf restore
+	for tok in "$@"; do
 		case "$tok" in
 			updateroot=http://*) urls="${urls} ${tok#*=}";;
 		esac
 	done
-	set +f
 	urls=${urls# }
-	if [ -z "$urls" ]; then
+
+	setf off; set -- $urls; setf restore
+	if [ $# -eq 0 ]; then
 		debug 1 "no updateroot urls configured in cmdline"
 		return 0
 	fi
 
 	if ! configure_networking; then
-		log_warn "failed configuring networking"
+		log_warn "failed configuring networking [$?]"
 		return 1
 	fi
 
 	# only mount rw if not already rw
-	local need_remount="false" ret=0
-	if ( : > "$rootmnt/.updateroot" ) >/dev/null 2>&1; then
-		mount -o remount,rw "$rootmnt" || {
-			log_warn "failed mount '$rootmnt' as rw.  Cannot use updateroot."
+	local need_remount="false" ret=0 created=true
+	local tfile="$rootmnt/.updateroot.touch"
+	[ -e "$tfile" ] || created=false
+	if ! ( : >> "$tfile" ) >/dev/null 2>&1; then
+		mount -o remount,rw "$rootmnt"
+		ret=$?
+		if $created; then
+			rm -f "$tfile"
+		fi
+		if [ $ret -ne 0 ]; then
+			log_warn "failed mount '$rootmnt' as rw [$ret]."
 			return 1;
-		}
+		fi
 		need_remount="true"
 	fi
 	
-	# subshell to protect expansion of urls
-	( set -f; extract_urls "$rootmnt" $urls )
+	extract_urls "$rootmnt" "$@"
 	ret=$?
 
 	if [ "${need_remount}" = "true" ]; then
 		mount -o remount,ro "$rootmnt" || {
-			log_warn "failed remounting root '$rootmnt' as ro!"
+			log_warn "failed remounting root '$rootmnt' as ro [$?]!"
 			return 1
 		}
 	fi
@@ -114,6 +156,6 @@ apply_updateroot() {
 
 . /scripts/functions
 
-apply_updateroot
+apply_updateroot "$rootmnt"
 
 # vi: ts=4 noexpandtab
