Initrd scripts are set -e, "A && action" is fatal.
LP: #1621615
bzr-revno: 117.1.1

diff --git a/dyn-netconf/scripts/init-bottom/cloud-initramfs-dyn-netconf b/dyn-netconf/scripts/init-bottom/cloud-initramfs-dyn-netconf
--- a/dyn-netconf/scripts/init-bottom/cloud-initramfs-dyn-netconf
+++ b/dyn-netconf/scripts/init-bottom/cloud-initramfs-dyn-netconf
@@ -30,6 +30,37 @@ PATH=/usr/sbin:/usr/bin:/sbin:/bin
 #DHCPLEASETIME='3600'
 #DOMAINSEARCH=''
 
+# superseded by isc-dhcp and such writing the file and supporting IPv6:
+#DEVICE=eno1
+#HOSTNAME=
+#DNSDOMAIN=
+#reason='PREINIT'
+#interface='eno1'
+#DEVICE=eno1
+#HOSTNAME=
+#DNSDOMAIN=
+#reason='FAIL'
+#interface='eno1'
+#DEVICE=eno1
+#HOSTNAME=
+#DNSDOMAIN=
+#reason='PREINIT6'
+#interface='eno1'
+#DEVICE=eno1
+#IPV6PROTO=dhcp6
+#IPV6ADDR=2001:67c:1562:8010:1::4324
+#IPV6NETMASK=64
+#IPV6DNS0=2001:67c:1562:8010::2:1
+#IPV6DOMAINSEARCH=
+#HOSTNAME=
+#DNSDOMAIN=
+#reason='BOUND6'
+#interface='eno1'
+#new_ip6_address='2001:67c:1562:8010:1::4324'
+#new_ip6_prefixlen='64'
+#new_dhcp6_name_servers='2001:67c:1562:8010::2:1'
+
+
 error() { echo "${0##*/}:" "$@" 1>&2; }
 configure_net_if_needed() {
 	# we want to call configure_networking if and only if ip= was seen
@@ -77,54 +108,62 @@ for f in /run/net-*.conf /tmp/net-*.conf; do
 
 	DEVICE=""; PROTO=""; IPV4ADDR=""; IPV4NETMASK=""; IPV4GATEWAY="";
 	IPV4DNS0=""; IPV4DNS1=""; DNSDOMAIN=""; DOMAINSEARCH=""; filename="";
-	IPV4PROTO=""; IPV6PROTO=""; IPV6ADDR=""; IPV6NETMASK="";
-	IPV6GATEWAY=""; IPV6DNS0=""; IPV6DNS1=""; IPV6DOMAINSEARCH="";
+        IPV4PROTO=""; IPV6PROTO=""; IPV6ADDR=""; IPV6NETMASK="";
+        IPV6GATEWAY=""; IPV6DNS0=""; IPV6DNS1=""; IPV6DOMAINSEARCH="";
 	. "$f"
 
 	if [ -z "$DEVICE" ]; then
 		error "WARNING: $f had no 'DEVICE' set"
 		continue
 	fi
+	# If IPv6 is supported, we get both of these, and at least one of them
+        # is set.  If we get both, use IPv4.
+	# Prior to that, PROTO was used, so we know it's IPv4 we want.
+	if [ -z "$IPV4PROTO" -a -z "$IPV6PROTO" ]; then
+		IPV4PROTO="$PROTO"
+	fi
 	# ipconfig on precise does not write PROTO.
-	if [ -z "$PROTO" ]; then
+	if [ -z "$IPV4PROTO" -a -z "$IPV6PROTO" ]; then
 		if [ -n "$filename" ]; then
-			PROTO="dhcp"
+			IPV4PROTO="dhcp"
 		else
-			PROTO="static"
+			IPV4PROTO="static"
 		fi
 	fi
 
+        # We need to use care, since the script is running set -e.
 	echo "manual $DEVICE"
-	if [ "$PROTO" = "dhcp" ]; then
+	if [ "$IPV4PROTO" = "dhcp" ]; then
 		echo "iface $DEVICE inet dhcp"
-	elif [ "$PROTO" = "static" ]; then
+	elif [ "$IPV4PROTO" = "static" ]; then
 		echo "iface $DEVICE inet static"
 		[ -n "$IPV4ADDR" ] && printf "\t%s\n" "address $IPV4ADDR"
 		[ -n "$IPV4NETMASK" ] && printf "\t%s\n" "netmask $IPV4NETMASK"
-		[ -n "$IPV4GATEWAY" ] && printf "\t%s\n" "gateway $IPV4GATEWAY"
-	fi
-	if [ "$IPV6PROTO" = "dhcp" ]; then
+		[ -z "$IPV4GATEWAY" ] || printf "\t%s\n" "gateway $IPV4GATEWAY"
+	elif [ "$IPV6PROTO" = "dhcp6" ]; then
 		echo "iface $DEVICE inet6 dhcp"
 	elif [ "$IPV6PROTO" = "static" ]; then
 		echo "iface $DEVICE inet6 static"
 		[ -n "$IPV6ADDR" ] && printf "\t%s\n" "address $IPV6ADDR"
 		[ -n "$IPV6NETMASK" ] && printf "\t%s\n" "netmask $IPV6NETMASK"
-		[ -n "$IPV6GATEWAY" ] && printf "\t%s\n" "gateway $IPV6GATEWAY"
+		[ -z "$IPV6GATEWAY" ] || printf "\t%s\n" "gateway $IPV6GATEWAY"
 	fi
+
+        nsline=""
 	if [ -n "$IPV4DNS0" -a "$IPV4DNS0" != "0.0.0.0" ]; then
 		nsline="${IPV4DNS0}"
-		[ -n "$IPV4DNS1" -a "$IPV4DNS1" != "0.0.0.0" ] &&
+		if [ -n "$IPV4DNS1" -a "$IPV4DNS1" = "0.0.0.0" ]; then
 			nsline="${nsline} ${IPV4DNS1}"
+                fi
+	elif [ -n "$IPV6DNS0" ]; then
+		nsline="${nsline} ${IPV6DNS0}"
+		[ -z "$IPV6DNS1" ] || nsline="${nsline} ${IPV6DNS1}"
 	fi
-	if [ -n "$IPV6DNS0" -a "$IPV6DNS0" != "0.0.0.0" ]; then
-		nsline="${IPV6DNS0}"
-		[ -n "$IPV6DNS1" -a "$IPV6DNS1" != "0.0.0.0" ] &&
-			nsline="${nsline} ${IPV6DNS1}"
-	fi
-	[ -n "$nsline" ] && printf "\tdns-nameservers %s\n" "$nsline"
-	[ -n "$DNSDOMAIN" -o -n "$DOMAINSEARCH" -o -n $IPV6DOMAINSEARCH] &&
-		SEARCH=" ${DNSDOMAIN} ${DOMAINSEARCH} ${IPV6DOMAINSEARCH}" &&
+	[ -z "$nsline" ] || printf "\tdns-nameservers %s\n" "$nsline"
+	if [ -n "${DNSDOMAIN}${DOMAINSEARCH}${IPV6DOMAINSEARCH}" ]; then
+		SEARCH=" ${DNSDOMAIN} ${DOMAINSEARCH} ${IPV6DOMAINSEARCH}"
 		printf "\tdns-search %s\n" "${SEARCH}"
+        fi
 done >> "$tmpf"
 
 [ -d /run/network ] || mkdir /run/network
